### ISSUE TITLE
Release v3

### ISSUE THREAD

**Issue by johanneswuerbach** [progrium/cedarish#16]
Some buildpacks (https://github.com/heroku/heroku-buildpack-ruby/commit/e375195ddbc3eff5b14e7c676fd5ea17c08792b6) start relying on https://github.com/progrium/cedarish/commit/de639ed1947278d389b97cd8946988f6edc5ac79.

Could you release a new version to use it in herokuish?

**Comment by progrium** [comment]
Yes. I will also add the PR release workflow I have in other projects.

**Comment by progrium** [comment]
Okay, so it's added. But it really sucks because it added a lot of size to the already large base image. In fact, GitHub Releases won't allow allow the tar because it's over 1GB now. :\
