### ISSUE TITLE
Tag cedar14 versions on Dockerhub

### ISSUE THREAD

**Issue by johanneswuerbach** [progrium/cedarish#17]
I would be great to be able to use something like "FROM progrium/cedar14:v2" inside a Dockerfile

**Comment by progrium** [comment]
Instead you can say:
```
FROM scratch
ADD . https://github.com/progrium/cedarish/releases/download/v2/cedarish-cedar14_v2.tar
```

**Comment by progrium** [comment]
Alternatively if you are orchestrating your build container outside of Docker toolchain (like buildkit and deis), you can do this:
```
docker import https://github.com/progrium/cedarish/releases/download/v2/cedarish-cedar14_v2.tar.gz progrium/cedarish:cedar14-v2
```
And use that in your build and your process will be significantly faster.
